ktor:
    application:
        modules:
            - example.com.ApplicationKt.module
    deployment:
        port: 8080
storage:
    token: "$TOKEN"
    driver: "com.mysql.jdbc.Driver"
    user: "$DB_USER"
    password: "$DB_PASSWORD"
    host: "$DB_HOST"
    db_port: "$DB_PORT"
    db_name: "$DB_NAME"